---
abstract: 'A simple SNMP AgentX subagent'
author:
  - 'Alexander Else <aelse@else.id.au>'
build_requires:
  NetSNMP::ASN: 0
  NetSNMP::agent: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SNMP-Agent
provides:
  SNMP::Agent:
    file: lib/SNMP/Agent.pm
    version: 0.04
requires:
  NetSNMP::ASN: 0
  NetSNMP::agent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
